// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOf3PqeewjeRvG8WTHasUMvMvH9b92Hj8',
    appId: '1:810302382239:web:ea060d6027fd8ed7c582aa',
    messagingSenderId: '810302382239',
    projectId: 'colab-care',
    authDomain: 'colab-care.firebaseapp.com',
    databaseURL: 'https://colab-care-default-rtdb.firebaseio.com',
    storageBucket: 'colab-care.appspot.com',
    measurementId: 'G-L0JG86MG56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-73aL5qZfg7mgW6nH0Zj9wlDeeAEyUWo',
    appId: '1:810302382239:android:1269b53783bf8451c582aa',
    messagingSenderId: '810302382239',
    projectId: 'colab-care',
    databaseURL: 'https://colab-care-default-rtdb.firebaseio.com',
    storageBucket: 'colab-care.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVq08A_vn15DMfmSEoSNceZswy9yLrI54',
    appId: '1:810302382239:ios:43fcc2b60e2cd9bcc582aa',
    messagingSenderId: '810302382239',
    projectId: 'colab-care',
    databaseURL: 'https://colab-care-default-rtdb.firebaseio.com',
    storageBucket: 'colab-care.appspot.com',
    iosClientId:
        '810302382239-6ifu3agf776q05miua3f1ko69lvu5bc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.colabCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVq08A_vn15DMfmSEoSNceZswy9yLrI54',
    appId: '1:810302382239:ios:eea14f139b446c23c582aa',
    messagingSenderId: '810302382239',
    projectId: 'colab-care',
    databaseURL: 'https://colab-care-default-rtdb.firebaseio.com',
    storageBucket: 'colab-care.appspot.com',
    iosClientId:
        '810302382239-6a5o6l17i5cage1qii6abb6vbro7mfmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.colabCare.RunnerTests',
  );
}
